apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
        - env:
            - name: JENKINS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_PASSWORD
                  name: env
            - name: JENKINS_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_USERNAME
                  name: env
          image: docker_in_jenkins
          name: jenkins
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-data
            - mountPath: /var/run/docker.sock
              name: docker-socket
      restartPolicy: Always
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
status: {}
